import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/models/order.dart';
import '../../../core/models/food_item.dart';
import '../../../data/repositories/repository_providers.dart';
import '../../auth/controllers/auth_controller.dart';

class CartState {
  final List<OrderItem> items;
  final String? canteenId;
  final String? canteenName;

  CartState({
    this.items = const [],
    this.canteenId,
    this.canteenName,
  });

  double get subtotal => items.fold(0, (sum, item) => sum + item.totalPrice);
  int get itemCount => items.fold(0, (sum, item) => sum + item.quantity);

  CartState copyWith({
    List<OrderItem>? items,
    String? canteenId,
    String? canteenName,
  }) {
    return CartState(
      items: items ?? this.items,
      canteenId: canteenId ?? this.canteenId,
      canteenName: canteenName ?? this.canteenName,
    );
  }
}

class OrderController extends Notifier<CartState> {
  @override
  CartState build() {
    return CartState();
  }

  void addToCart(FoodItem foodItem, String canteenId, String canteenName) {
    if (state.canteenId != null && state.canteenId != canteenId) {
      // Clear cart if switching canteens (standard policy)
      state = CartState();
    }

    final existingIndex = state.items.indexWhere((i) => i.foodItem.id == foodItem.id);
    
    if (existingIndex != -1) {
      final updatedItems = List<OrderItem>.from(state.items);
      final item = updatedItems[existingIndex];
      updatedItems[existingIndex] = OrderItem(
        foodItem: item.foodItem,
        quantity: item.quantity + 1,
      );
      state = state.copyWith(items: updatedItems);
    } else {
      state = state.copyWith(
        items: [...state.items, OrderItem(foodItem: foodItem, quantity: 1)],
        canteenId: canteenId,
        canteenName: canteenName,
      );
    }
  }

  void removeFromCart(String foodItemId) {
    final updatedItems = state.items.where((i) => i.foodItem.id != foodItemId).toList();
    state = state.copyWith(items: updatedItems);
    if (updatedItems.isEmpty) {
      state = CartState();
    }
  }

  void clearCart() {
    state = CartState();
  }

  Future<void> checkout() async {
    final user = ref.read(authControllerProvider);
    if (user == null || state.items.isEmpty) return;

    final order = Order(
      id: '', // Generated by backend
      canteenId: state.canteenId!,
      canteenName: state.canteenName!,
      items: state.items,
      totalAmount: state.subtotal,
      status: OrderStatus.accepted, // Default initial status
      type: OrderType.pickup, // Default
      orderTime: DateTime.now(),
      estimatedMinutes: 15,
    );

    await ref.read(orderRepositoryProvider).placeOrder(order);
    clearCart();
  }
}

final orderControllerProvider = NotifierProvider<OrderController, CartState>(OrderController.new);

// Active Orders State (For tracking)
class ActiveOrdersController extends Notifier<List<Order>> {
  @override
  List<Order> build() {
    final user = ref.watch(authControllerProvider);
    if (user == null) return [];

    // Listen to realtime orders from Supabase
    ref.listen(userOrdersStreamProvider(user.id), (previous, next) {
      if (next.hasValue) {
        state = next.value!;
      }
    });

    return [];
  }
}

final activeOrdersProvider = NotifierProvider<ActiveOrdersController, List<Order>>(ActiveOrdersController.new);

final userOrdersStreamProvider = StreamProvider.family<List<Order>, String>((ref, userId) {
  return ref.watch(orderRepositoryProvider).watchUserOrders(userId);
});

